### ISSUE TITLE
Stop moves from being interruptable

### ISSUE THREAD

**Issue by MasterTailer** [MasterTailer/DIGITAiL#14]
.. on the moves page

Also possibly a traffic light system to prevent moves being triggered too soon after a move

**Comment by leinir** [comment]
When Everyday Mode is on, use a simple overlay with a progress spinner to show when the next command might be sent

**Comment by leinir** [comment]
Fixed in 9bb0b324181952fb4aa99aa7b6256c36e0bbb4ae (apk uploaded 2019/02/14 12:37)
