### ISSUE TITLE
Give paired tails human names

### ISSUE THREAD

**Issue by MasterTailer** [MasterTailer/DIGITAiL#19]

**Comment by narek-h** [comment]
@MasterTailer 
would like to clarify this a bit. 
Where to get the names? If we suppose to use some random names, do we need to create some list?

**Comment by MasterTailer** [comment]
No, we need to ask the user to name a tail - so keyboard shown, text string entered, and then saved.
When the tail is next detected, the human name is shown..

**Comment by narek-h** [comment]
@MasterTailer , we can close this one right ?  PR is merged. 
(closing now, please reopen in case).
