### ISSUE TITLE
Rename Tail Lights button to Glow Tips

### ISSUE THREAD

**Issue by MasterTailer** [MasterTailer/DIGITAiL#23]
Just the UI button, though changing the underlying code is probably a good idea too

**Comment by gilmanov-ildar** [comment]
Renamed Tail Lights visible texts to Glow Tips.

Also it would be nice to rename all controls and files from Tail Lights to Glow Tips, in order to reflect code structure to view structure.

https://github.com/MasterTailer/DIGITAiL/pull/26
