### ISSUE TITLE
Rename `settings.h` and `settings.cpp` to `appsettings.h` and `appsettings.cpp`

### ISSUE THREAD

**Issue by gilmanov-ildar** [MasterTailer/DIGITAiL#28]
It is better to keep file names as a main class inside.

**Comment by gilmanov-ildar** [comment]
Done, the pull request: https://github.com/MasterTailer/DIGITAiL/pull/38

**Comment by leinir** [comment]
Fixed in 25b61bbef5a4a088ff7a4175a858f5cb18377a50
