### ISSUE TITLE
Use CamelCase for file names

### ISSUE THREAD

**Issue by gilmanov-ildar** [MasterTailer/DIGITAiL#29]
Now we have filenames like this: `filterproxymodel.h`, it is hard to read and understand them quickly. More usable way is using CamelCase, for example: `FilterProxyModel.h`

**Comment by gilmanov-ildar** [comment]
https://github.com/MasterTailer/DIGITAiL/pull/38

**Comment by leinir** [comment]
Fixed in 25b61bbef5a4a088ff7a4175a858f5cb18377a50
