### ISSUE TITLE
Add a perpetual notification to the service

### ISSUE THREAD

**Issue by leinir** [MasterTailer/DIGITAiL#31]
In the style of other control systems (and routing tools and whatnot), we need a notification on Android when the tail is connected, to ensure that the service is not killed mercilessly while we're waiting on it to do things with that connected tail.

**Comment by MasterTailer** [comment]
Currently we can manually add an app to an ignore list when telling the system to purge battery draining background apps. But this doesnt fix the lock screen off / tail off behaviour.
