### ISSUE TITLE
Remove rhs context menu 

### ISSUE THREAD

**Issue by MasterTailer** [MasterTailer/DIGITAiL#33]
..and create a settings menu item on the LHS menu. Inside it, lets have an Advanced settings button within.

**Comment by gilmanov-ildar** [comment]
![image](https://user-images.githubusercontent.com/15459404/53347445-ab40ec80-394b-11e9-8434-074c286b5c3c.png)

![image](https://user-images.githubusercontent.com/15459404/53347468-b5fb8180-394b-11e9-8f2a-c936618df692.png)
