### ISSUE TITLE
Quit app when backing out from front page

### ISSUE THREAD

**Issue by leinir** [MasterTailer/DIGITAiL#34]
The way apps with more serious stuff going on in the background tend to handle force-disconnect-and-quit scenarios is to let the user do this by pressing back on the front page of the app, and then being prompted with either a question asking if they want to quit or not, or prompted to press back again to quit (which will then be honoured if done within a certain amount of time, usually the same amount of time as the notification is shown). We would want to go with the second of these options.

**Comment by gilmanov-ildar** [comment]
Quit the app when a user tap to back button when `Welcome` page is active.
Should be tested on Android device.
And later we should add `Toast` to show message something like this: "To quit the app tap back button again".

**Comment by gilmanov-ildar** [comment]
Pull request: https://github.com/MasterTailer/DIGITAiL/pull/56
