### ISSUE TITLE
On about page, change..

### ISSUE THREAD

**Issue by MasterTailer** [MasterTailer/DIGITAiL#39]
"DIGITAiL Controller 1.0" to DIGITAiL App v.1 (text at top)

Also "Dan Leinir Tuthra Jensen " and email address should be left justified.

**Comment by gilmanov-ildar** [comment]
![image](https://user-images.githubusercontent.com/15459404/53344695-e3ddc780-3945-11e9-80c0-6c870aa767ef.png)

Pull request: https://github.com/MasterTailer/DIGITAiL/pull/49
