### ISSUE TITLE
Easter egg!

### ISSUE THREAD

**Issue by MasterTailer** [MasterTailer/DIGITAiL#5]
When you touch the graphic on the lh menu in an odd way :D

**Comment by gilmanov-ildar** [comment]
When a user clicks 5 times in 1.5 seconds to the Menu banner we switch 
developer mode flag and show message box to user.

![image](https://user-images.githubusercontent.com/15459404/53637239-358f9600-3c55-11e9-980a-5d39bb23dcba.png)

![image](https://user-images.githubusercontent.com/15459404/53637276-4b9d5680-3c55-11e9-8742-bb3e4d8de63e.png)

Pull request: https://github.com/MasterTailer/DIGITAiL/pull/54
