### ISSUE TITLE
Add Glash

### ISSUE THREAD

**Issue by MasterTailer** [MasterTailer/DIGITAiL#57]
Glash mode to be enabled in developer menu. No more details here for obvious reasons. Extra content in Telegram chat.

**Comment by gilmanov-ildar** [comment]
Pull request: https://github.com/MasterTailer/DIGITAiL/pull/63

**Comment by gilmanov-ildar** [comment]
Should be tested on a read Android device

**Comment by MasterTailer** [comment]
Sound play doesnt work..

**Comment by gilmanov-ildar** [comment]
Ok, I will test it on Android later at this week

**Comment by gilmanov-ildar** [comment]
Pull request: https://github.com/MasterTailer/DIGITAiL/pull/74
