### ISSUE TITLE
rename LED pattern buttons:

### ISSUE THREAD

**Issue by MasterTailer** [MasterTailer/DIGITAiL#58]
LEDREC - intermittent (on/off) - changed to BLINK
LEDTRI - triangular (fade in/out) -  changed to TRIANGLE
LEDSAW - sawtooth (fade in/off) -  changed to SAWTOOTH
LEDSOS - Morse SOS-  changed to MORSE
LEDFLA - flame simulation -  changed to FLAME
LEDSTR - strobo -  changed to STROBE

**Comment by narek-h** [comment]
@MasterTailer , a couple of small things to confirm. 

1. On current UI we have 'LEDBEA - Beacon' , don't we need to rename it ? 
2. If we keep 'Beacon' as is,  then maybe makes sense to make it all uppercase like others ? 

Please let me know. 
   Narek

**Comment by MasterTailer** [comment]
Sorry yes, the missing one should be BEACON
