### ISSUE TITLE
Battery gauge to be above mode  buttons

### ISSUE THREAD

**Issue by MasterTailer** [MasterTailer/DIGITAiL#6]
..where the connection stuff goes - once connected!

**Comment by gilmanov-ildar** [comment]
Extracted TailBattery to separated qml control and move it from left Drawer to the Welcome view

https://github.com/MasterTailer/DIGITAiL/pull/27

![image](https://user-images.githubusercontent.com/15459404/52271389-15322b80-2976-11e9-81c2-ba7b748fd728.png)

![image](https://user-images.githubusercontent.com/15459404/52271412-20855700-2976-11e9-92b4-88756e2297e9.png)
