### ISSUE TITLE
Auto-reconnect if the tail disconnects without user intervention

### ISSUE THREAD

**Issue by MasterTailer** [MasterTailer/DIGITAiL#61]
and keep reconnecting unless a check box in settings is unticked 

-- Use Auto-reconnect if your tail drops the connection? X

**Comment by gilmanov-ildar** [comment]
Pull request: https://github.com/MasterTailer/DIGITAiL/pull/62

**Comment by MasterTailer** [comment]
Probably all good, but I need to test more!
