### ISSUE TITLE
Put "forget recorded names"

### ISSUE THREAD

**Issue by MasterTailer** [MasterTailer/DIGITAiL#78]
in settings menu

**Comment by gilmanov-ildar** [comment]
We should just add the "Forget recorded names" menu item to settings menu, or also add an actions?

**Comment by gilmanov-ildar** [comment]
Just have a button that erases any previously recorded tail names please

**Comment by MasterTailer** [comment]
The button should delete any previously recorded tail names - so that a 
tail that has already been "seen" by the app would appear new.

**Comment by gilmanov-ildar** [comment]
Pull request: https://github.com/MasterTailer/DIGITAiL/pull/85
