### ISSUE TITLE
Instructions link

### ISSUE THREAD

**Issue by MasterTailer** [MasterTailer/DIGITAiL#79]
in the about page

**Comment by gilmanov-ildar** [comment]
@MasterTailer , as I got we should add an "Instructions" link to the About page, but could you please tell me what the url the link should refer?

**Comment by gilmanov-ildar** [comment]
So instructions should link to http://thetailcompany.com/digitail.pdf

**Comment by MasterTailer** [comment]
Exactly.

**Comment by gilmanov-ildar** [comment]
@MasterTailer, it is impossible while we are using the `Kirigami.AboutPage` and do not want to patch it.

**Comment by MasterTailer** [comment]
Move this link to settings then please

**Comment by gilmanov-ildar** [comment]
Pull request: https://github.com/MasterTailer/DIGITAiL/pull/90
