### ISSUE TITLE
Check whether Bluetooth is switched off / no BT no hardware! And if its off, show message

### ISSUE THREAD

**Issue by MasterTailer** [MasterTailer/DIGITAiL#8]

**Comment by MasterTailer** [comment]
So the core class for that work would be... QBluetoothLocalDevice, and the function is https://doc.qt.io/qt-5/qbluetoothlocaldevice.html#powerOn

And to work out whether it's on or not, use https://doc.qt.io/qt-5/qbluetoothlocaldevice.html#hostMode

**Comment by MasterTailer** [comment]
https://doc.qt.io/QtDeviceUtilities/bluetoothdevice.html#available-prop

**Comment by MasterTailer** [comment]
It should also be the same code on desktop linux, the backend will be different but the code in the app should be the same :)

**Comment by narek-h** [comment]
@MasterTailer , 
we need to check this (and show a message) on app start and when the BT state is changed, correct ? 
I mean, when the GUI is just shown and BT is off, we'll display a warning.

**Comment by MasterTailer** [comment]
Yes that is correct
